version: '3'

tasks:
  :build:
    cmds:
      - 'go build -o dist/app'
    sources:
      - ./*.go,
      - ./**/*.go

  :run-arch:
    cmds:
      - 'docker-compose run --rm archlinux {{.CLI_ARGS}}'

  :run-app:
    cmds:
      - task: :build
        silent: true
      - task: :run-arch

